-- CREATING DIFFERENT ROLES TO MANAGE OUR SYSTEM
CREATE USER DB_ADMIN IDENTIFIED BY "Dmdd99@dbadmin";
CREATE USER DB_EMPLOYEE IDENTIFIED BY "Dmdd99@employee";
CREATE USER DB_CUSTOMER IDENTIFIED BY "Dmdd99@customer";


-- GRANTING PERMISSION TO CREATE TABLES, PACKAGES, ETC.
GRANT CONNECT, RESOURCE TO DB_ADMIN;
GRANT CREATE SESSION TO DB_ADMIN;
GRANT UNLIMITED TABLESPACE TO DB_ADMIN;
GRANT CREATE VIEW TO DB_ADMIN;


-- GRANTING PERMISSION TO DB_EMPLOYEE, DB_CUSTOMER
GRANT CONNECT TO DB_EMPLOYEE, DB_CUSTOMER;
GRANT CREATE SESSION TO DB_EMPLOYEE, DB_CUSTOMER;


