
-- Get annual bank statement for a given account
SELECT * FROM DB_ADMIN.TRANSACTION 
WHERE TRANS_DATE BETWEEN '01-JAN-22' AND '31-DEC-22' AND ACC_NO = 213421;

-- Get customer details whose account balance is greater than 2000
SELECT * FROM DB_ADMIN.CUSTOMER C 
JOIN DB_ADMIN.ACCOUNT A ON C.CUST_ID = A.CUST_ID 
WHERE A.BALANCE > 2000;

-- Get all customers with checking account and zipcode is 02130
SELECT * FROM DB_ADMIN.CUSTOMER C 
JOIN DB_ADMIN.ACCOUNT A ON C.CUST_ID = A.CUST_ID 
WHERE A.ACC_TYPE = 'CHECKIN' AND C.ZIPCODE = 02130;

-- Get the total fund in a branch
SELECT B.BRANCH_ID, B.NAME, SUM(A.BALANCE) FROM DB_ADMIN.ACCOUNT A
JOIN DB_ADMIN.CUSTOMER C ON C.CUST_ID = A.CUST_ID
JOIN DB_ADMIN.EMPLOYEE E ON E.EMP_ID = C.EMP_ID
JOIN DB_ADMIN.BRANCH B ON E.BRANCH_ID = B.BRANCH_ID
GROUP BY (B.BRANCH_ID, B.NAME);

-- Count the number of transaction by its type
SELECT TRANS_TYPE, COUNT(*) FROM DB_ADMIN.TRANSACTION 
GROUP BY TRANS_TYPE;

-- Get all customers under a given branch
SELECT * FROM DB_ADMIN.CUSTOMER C
JOIN DB_ADMIN.EMPLOYEE E ON E.EMP_ID = C.EMP_ID
JOIN DB_ADMIN.BRANCH B ON E.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID = 1;


SELECT * FROM DB_ADMIN.ACCOUNT;
SELECT * FROM DB_ADMIN.TRANSACTION;