-- *************** VIEWS *****************/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TOTAL_BALANCE_PER_BRANCH"
AS
SELECT B.BRANCH_ID AS BRANCH_ID, B.NAME AS BRANCH_NAME, COUNT(A.ACC_NO) AS TOTAL_ACC, SUM(A.BALANCE) AS TOTAL_BAL 
FROM DB_ADMIN.ACCOUNT A
JOIN DB_ADMIN.CUSTOMER C ON C.CUST_ID = A.CUST_ID
JOIN DB_ADMIN.EMPLOYEE E ON E.EMP_ID = C.EMP_ID
JOIN DB_ADMIN.BRANCH B ON E.BRANCH_ID = B.BRANCH_ID
GROUP BY (B.BRANCH_ID, B.NAME)
ORDER BY B.BRANCH_ID;

SELECT * FROM TOTAL_BALANCE_PER_BRANCH;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "COUNT_TRANSACTION_TYPE"
AS
SELECT TRANS_TYPE AS TRANSACTION_TYPE, COUNT(*) AS TOTAL_TYPE FROM DB_ADMIN.TRANSACTION 
GROUP BY TRANS_TYPE;

SELECT * FROM COUNT_TRANSACTION_TYPE;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ACTIVE_CUST"
AS
SELECT C.CUST_ID AS CID, C.FNAME || ' ' || C.LNAME AS CUST_NAME, A.ACC_NO AS ACCOUNT_NO, A.ACC_TYPE AS TYPE FROM DB_ADMIN.CUSTOMER C
JOIN DB_ADMIN.ACCOUNT A ON C.CUST_ID = A.CUST_ID
WHERE A.STATUS = 'ACTIVE';

SELECT * FROM ACTIVE_CUST;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEBITED_LAST_WEEK"
AS
SELECT TRANS_ID, PRI_ACC_NO, TRANS_TYPE, TRANS_DATE, AMOUNT FROM DB_ADMIN.TRANSACTION
WHERE TRUNC(TRANS_DATE) > TRUNC(SYSDATE)-7 AND DEBIT_CREDIT_FLAG = 'DEBIT';

SELECT * FROM DEBITED_LAST_WEEK;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "CREDITED_LAST_WEEK"
AS
SELECT TRANS_ID, PRI_ACC_NO, TRANS_TYPE, TRANS_DATE, AMOUNT FROM DB_ADMIN.TRANSACTION
WHERE TRUNC(TRANS_DATE) > TRUNC(SYSDATE)-7 AND DEBIT_CREDIT_FLAG = 'CREDIT';

SELECT * FROM CREDITED_LAST_WEEK;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "EMP_5YRS_ABOVE_EXP"
AS
SELECT EMP_ID, FNAME || ' ' || LNAME AS EMP_NAME, JOINING_DATE FROM DB_ADMIN.EMPLOYEE
WHERE EXTRACT(YEAR FROM JOINING_DATE) < EXTRACT(YEAR FROM SYSDATE)-5;

SELECT * FROM EMP_5YRS_ABOVE_EXP;

------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "MORE_THAN_ONE_ACC"
AS
SELECT C.FNAME || ' ' || C.LNAME AS CUST_NAME, COUNT(C.CUST_ID) AS TOTAL_ACCOUNTS 
FROM DB_ADMIN.CUSTOMER C
JOIN DB_ADMIN.ACCOUNT A ON C.CUST_ID = A.CUST_ID
WHERE A.STATUS = 'ACTIVE'
GROUP BY (C.FNAME || ' ' || C.LNAME, C.CUST_ID)
HAVING COUNT(C.CUST_ID) > 1;

SELECT * FROM MORE_THAN_ONE_ACC;

------------------



